export const GET_ALL_CHAMPULL = 'GET_ALL_CHAMPULL';
export const GET_ALL_CHAMPULL_ASYNC = 'GET_ALL_CHAMPOO_ASYNC';

export const ADD_CHAMP_CHAMPULL = 'ADD_CHAMP_CHAMPULL';
export const ADD_CHAMP_CHAMPULL_ASYNC = 'ADD_CHAMP_CHAMPULL_ASYNC';

export const DELETE_CHAMP_CHAMPULL = 'DELETE_CHAMP_CHAMPULL';
export const DELETE_CHAMP_CHAMPULL_ASYNC = 'DELETE_CHAMP_CHAMPULL_ASYNC';
